### ISSUE TITLE
Compatibility issue in Vaadin 22/23

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/ErrorWindowAddon#40]
The demo site for Vaadin 22 and 23 fails to display the error window when the addon "production mode" toggle is configured as `false` (Vaadin _production mode_ is `true` though)

![image](https://user-images.githubusercontent.com/11554739/167956061-e9ce93a3-e916-4805-9b98-67cc9def89f1.png)

**Comment by javier-godoy** [comment]
The exception is 
```
java.lang.NoSuchMethodError: 'org.jsoup.nodes.Element org.jsoup.nodes.Element.traverse(org.jsoup.select.NodeVisitor)'
        at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.inspectTwoWayBindings(TemplateDataAnalyzer.java:238) ~[flow-polymer-template-9.0.10.jar!/:9.0.10]
        at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:227) ~[flow-polymer-template-9.0.10.jar!/:9.0.10]
        at com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$null$23ee5b4f$1(TemplateInitializer.java:95) ~[flow-polymer-template-9.0.10.jar!/:9.0.10]
        at com.vaadin.flow.internal.ReflectionCache.lambda$wrapValueProvider$d0062d93$1(ReflectionCache.java:93) ~[flow-server-9.0.10.jar!/:9.0.10]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[na:na]
        at com.vaadin.flow.internal.ReflectionCache.get(ReflectionCache.java:110) ~[flow-server-9.0.10.jar!/:9.0.10]
        at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:96) ~[flow-polymer-template-9.0.10.jar!/:9.0.10]
        at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:95) ~[flow-polymer-template-9.0.10.jar!/:9.0.10]
        at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:110) ~[flow-polymer-template-9.0.10.jar!/:9.0.10]
        at org.vaadin.olli.ClipboardHelper.<init>(ClipboardHelper.java:31) ~[clipboardhelper-1.2.0.jar!/:1.2.0]
        at com.flowingcode.vaadin.addons.errorwindow.ErrorWindow.createMainLayout(ErrorWindow.java:161) ~[error-window-vaadin-3.2.1-SNAPSHOT.jar!/:3.2.1-SNAPSHOT]
```

`Element.traverse(org.jsoup.select.NodeVisitor)` was [added in jsoup 1.12.2](https://javadoc.io/doc/org.jsoup/jsoup/1.12.2/org/jsoup/nodes/Element.html). For some reason the demos use jsoup-1.11.3.
